Batch measurements (#19)
This introduces a new configuration setting to specify the maximum
number of measurements to send to our aggregator cluster. Some
applications were generating more than what we could process in a single
request, and we were getting errors like:

```
ERROR: 2018/10/04 21:39:41 Could not POST measurements: 500 <nil>
DEBUG: 2018/10/04 21:39:45 Got 42287 measurements
DEBUG: 2018/10/04 21:39:46 posting data to http://example.org/api/v4/update, payload is 9152185 bytes
DEBUG: 2018/10/04 21:39:46 request succeeded (500): {"type":"error","message":"EntityStreamSizeException: EntityStreamSizeException: actual entity size (None) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream."}<Paste>
```